/**
 * seedIndiaJobs.js
 * Inserts the "IT Companies Hiring - October 2026 (India)" job listings
 * into the existing database WITHOUT clearing any existing data.
 *
 * Run from the backend directory:
 *   node src/scripts/seedIndiaJobs.js
 */

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

import Job from '../models/Job.js';
import { generateJobHash } from '../utils/duplicateDetector.js';

const INDIA_JOBS = [
  // ── IT services majors ───────────────────────────────────────────────────────
  {
    companyName: 'TCS',
    jobTitle: 'Software Developer (Java/.NET/React/AI)',
    category: 'IT services majors',
    hiringRoles: 'Developers (Java/.NET/React), cloud, SAP, testing, AI/data, Ninja/Digital/Prime fresher tracks',
    careerPageUrl: 'https://www.tcs.com/careers',
    ctcEntry: '3.4 - 9 LPA (Ninja/Digital/Prime)',
    ctcExperienced: '6 - 14 LPA',
    salaryMin: 340000, salaryMax: 900000,
    location: 'Chennai / Bangalore / Multiple',
    skills: ['Java', '.NET', 'React', 'Cloud', 'SAP', 'AI', 'Data Engineering', 'Testing'],
    comments: 'Added ~9,300 net in Q1 FY27 (biggest in 4 yrs). TCS iON lists many Chennai fresher jobs with deadlines through Oct 31. NQT registration closing ~Oct 7.',
    minExp: 0, maxExp: 3,
  },
  {
    companyName: 'Infosys',
    jobTitle: 'Systems Engineer / Specialist Programmer',
    category: 'IT services majors',
    hiringRoles: 'Systems Engineer, Specialist Programmer, DevOps, cloud, SAP, data/AI',
    careerPageUrl: 'https://www.infosys.com/careers/',
    ctcEntry: '3.6 - 9.5 LPA (SE to Specialist Programmer)',
    ctcExperienced: '6 - 15 LPA',
    salaryMin: 360000, salaryMax: 950000,
    location: 'Bangalore / Pune / Multiple',
    skills: ['DevOps', 'Cloud', 'SAP', 'Data Engineering', 'AI', 'Java', 'Python'],
    comments: 'Plans at least 20,000 fresher hires in FY27. Lateral hiring is selective.',
    minExp: 0, maxExp: 4,
  },
  {
    companyName: 'Wipro',
    jobTitle: 'Project Engineer (Full Stack / Cloud)',
    category: 'IT services majors',
    hiringRoles: 'Project Engineer, Java/.NET full stack, cloud, cybersecurity, SAP',
    careerPageUrl: 'https://careers.wipro.com/',
    ctcEntry: '3.5 - 6.5 LPA (Elite to Turbo)',
    ctcExperienced: '6 - 14 LPA',
    salaryMin: 350000, salaryMax: 650000,
    location: 'Bangalore / Multiple',
    skills: ['Java', '.NET', 'Full Stack', 'Cloud', 'Cybersecurity', 'SAP'],
    comments: 'Q1 profit nearly flat. Net adds small and partly from an acquisition.',
    minExp: 0, maxExp: 3,
  },
  {
    companyName: 'HCLTech',
    jobTitle: 'Graduate Engineer Trainee (Cloud / Embedded)',
    category: 'IT services majors',
    hiringRoles: 'Graduate Engineer Trainee, embedded C/C++, cloud, SAP, cybersecurity',
    careerPageUrl: 'https://www.hcltech.com/careers',
    ctcEntry: '3.5 - 5 LPA',
    ctcExperienced: '6 - 14 LPA',
    salaryMin: 350000, salaryMax: 500000,
    location: 'Chennai / Bangalore',
    skills: ['C', 'C++', 'Embedded', 'Cloud', 'SAP', 'Cybersecurity'],
    comments: 'Embedded C/C++ drive (Chennai/Bangalore) open until Oct 31. Overall headcount falling.',
    minExp: 0, maxExp: 2,
  },
  {
    companyName: 'Cognizant',
    jobTitle: 'Programmer Analyst / Jr. Software Engineer',
    category: 'IT services majors',
    hiringRoles: 'Programmer Analyst, Jr. Software Engineer (Java/Python/JS), Java+AWS leads',
    careerPageUrl: 'https://careers.cognizant.com/',
    ctcEntry: '4 - 7 LPA (GenC / GenC Next)',
    ctcExperienced: '7 - 16 LPA',
    salaryMin: 400000, salaryMax: 700000,
    location: 'Hyderabad / Chennai / Multiple',
    skills: ['Java', 'Python', 'JavaScript', 'AWS', 'Microservices'],
    comments: 'Jr. Software Engineer (microservices) role in Hyderabad posted Sept 16. Very large Chennai presence.',
    minExp: 0, maxExp: 3,
  },
  {
    companyName: 'Accenture',
    jobTitle: 'Associate Software Engineer (Cloud / SAP)',
    category: 'IT services majors',
    hiringRoles: 'Associate Software Engineer, packaged app dev (SAP/Salesforce/Oracle), cloud, security',
    careerPageUrl: 'https://www.accenture.com/in-en/careers',
    ctcEntry: '4.5 - 6.5 LPA (up to 8 specialist)',
    ctcExperienced: '8 - 18 LPA',
    salaryMin: 450000, salaryMax: 650000,
    location: 'Chennai / Bangalore / Multiple',
    skills: ['SAP', 'Salesforce', 'Oracle', 'Cloud', 'Cybersecurity'],
    comments: 'Hires year-round. Chennai operations roles seen on aggregators.',
    minExp: 0, maxExp: 3,
  },
  {
    companyName: 'Capgemini',
    jobTitle: 'Software Engineer / SAP S/4HANA Analyst',
    category: 'IT services majors',
    hiringRoles: 'Software Engineer, Analyst, SAP S/4HANA, cloud/data',
    careerPageUrl: 'https://www.capgemini.com/in-en/careers/',
    ctcEntry: '3.8 - 7.5 LPA',
    ctcExperienced: '7 - 16 LPA',
    salaryMin: 380000, salaryMax: 750000,
    location: 'Bengaluru / Chennai / Pune',
    skills: ['SAP S/4HANA', 'Cloud', 'Data Engineering', 'Software Engineering'],
    comments: 'Software Engineer opening covers Bengaluru, Chennai, Pune. Runs frequent virtual drives.',
    minExp: 0, maxExp: 4,
  },
  {
    companyName: 'Tech Mahindra',
    jobTitle: 'Software Engineer (Network/5G/Cloud)',
    category: 'IT services majors',
    hiringRoles: 'Software Engineer, network/5G, testing, cloud, support',
    careerPageUrl: 'https://careers.techmahindra.com/',
    ctcEntry: '3.5 - 5 LPA',
    ctcExperienced: '6 - 14 LPA',
    salaryMin: 350000, salaryMax: 500000,
    location: 'Hyderabad / Multiple',
    skills: ['Networking', '5G', 'Testing', 'Cloud', 'Support'],
    comments: 'Virtual drive for international voice roles listed Oct 5-10 (Hyderabad). Headcount down; precision hiring.',
    minExp: 0, maxExp: 3,
  },
  {
    companyName: 'LTIMindtree',
    jobTitle: 'Full Stack / Data Engineering Developer',
    category: 'IT services majors',
    hiringRoles: 'Full stack, data engineering, cloud, SAP, AI',
    careerPageUrl: 'https://www.ltimindtree.com/careers/',
    ctcEntry: '4 - 6 LPA',
    ctcExperienced: '7 - 16 LPA',
    salaryMin: 400000, salaryMax: 600000,
    location: 'Bangalore / Pune / Multiple',
    skills: ['Full Stack', 'Data Engineering', 'Cloud', 'SAP', 'AI'],
    comments: 'Headcount fell in Q1. Lateral hiring selective.',
    minExp: 0, maxExp: 4,
  },
  {
    companyName: 'NTT DATA',
    jobTitle: 'Associate DevOps Engineer / MS Engineer L1',
    category: 'IT services majors',
    hiringRoles: 'Associate DevOps Engineer, MS Engineer L1, cloud/infra',
    careerPageUrl: 'https://www.nttdata.com/global/en/careers',
    ctcEntry: '3.5 - 6 LPA',
    ctcExperienced: '6 - 15 LPA',
    salaryMin: 350000, salaryMax: 600000,
    location: 'Bengaluru / Mumbai / Chennai',
    skills: ['DevOps', 'Cloud', 'Infrastructure', 'Linux', 'AWS'],
    comments: 'Off-campus drives for DevOps (Bengaluru) and MS Engineer L1 (Bangalore, Mumbai, Chennai) listed Oct 2.',
    minExp: 0, maxExp: 3,
  },
  {
    companyName: 'IBM',
    jobTitle: 'Associate Software Engineer (Cloud/AI)',
    category: 'IT services majors',
    hiringRoles: 'Associate Software Engineer, consulting, cloud, AI',
    careerPageUrl: 'https://www.ibm.com/careers',
    ctcEntry: '4.5 - 8 LPA',
    ctcExperienced: '8 - 20 LPA',
    salaryMin: 450000, salaryMax: 800000,
    location: 'Bangalore',
    skills: ['Cloud', 'AI', 'Consulting', 'Java', 'Python'],
    comments: 'Associate Software Engineer drive in Bangalore listed on aggregators.',
    minExp: 0, maxExp: 3,
  },
  {
    companyName: 'CGI',
    jobTitle: 'Associate Software Engineer (Java/.NET)',
    category: 'IT services majors',
    hiringRoles: 'Associate Software Engineer, Java/.NET, testing',
    careerPageUrl: 'https://www.cgi.com/en/careers',
    ctcEntry: '4 - 6 LPA',
    ctcExperienced: '7 - 16 LPA',
    salaryMin: 400000, salaryMax: 600000,
    location: 'Bangalore / Chennai',
    skills: ['Java', '.NET', 'Testing', 'Software Engineering'],
    comments: 'Apprentice/associate roles in Bangalore listed. Big Chennai delivery centre.',
    minExp: 0, maxExp: 3,
  },
  {
    companyName: 'Unisys',
    jobTitle: 'Associate Engineer / Software Application Engineer',
    category: 'IT services majors',
    hiringRoles: 'Associate Engineer, Software Application Engineer',
    careerPageUrl: 'https://www.unisys.com/careers/',
    ctcEntry: '3.5 - 6 LPA',
    ctcExperienced: '6 - 14 LPA',
    salaryMin: 350000, salaryMax: 600000,
    location: 'Multiple',
    skills: ['Software Engineering', 'Java', 'Cloud', 'Infrastructure'],
    comments: 'Entry-level drives seen on aggregators.',
    minExp: 0, maxExp: 2,
  },
  // ── Mid-size IT & engineering ────────────────────────────────────────────────
  {
    companyName: 'Mphasis',
    jobTitle: 'Software Engineer (Cloud / Data / Testing)',
    category: 'Mid-size IT & engineering',
    hiringRoles: 'Software engineer, cloud, data, testing',
    careerPageUrl: 'https://careers.mphasis.com/',
    ctcEntry: '3.5 - 6 LPA',
    ctcExperienced: '7 - 16 LPA',
    salaryMin: 350000, salaryMax: 600000,
    location: 'Multiple',
    skills: ['Cloud', 'Data Engineering', 'Testing', 'BFSI Tech'],
    comments: 'BFSI-heavy. Hires through the year.',
    minExp: 0, maxExp: 4,
  },
  {
    companyName: 'Persistent Systems',
    jobTitle: 'Java/.NET/React Developer',
    category: 'Mid-size IT & engineering',
    hiringRoles: 'Java/.NET/React developers, data, product engineering',
    careerPageUrl: 'https://www.persistent.com/careers/',
    ctcEntry: '5 - 9 LPA',
    ctcExperienced: '10 - 22 LPA',
    salaryMin: 500000, salaryMax: 900000,
    location: 'Hyderabad / Pune / Bangalore',
    skills: ['Java', '.NET', 'React', 'Data Engineering', 'Product Engineering'],
    comments: 'Strong engineering culture. Hyderabad, Pune, Bangalore main hubs.',
    minExp: 0, maxExp: 4,
  },
  {
    companyName: 'Hexaware',
    jobTitle: 'Full Stack / SAP / Cloud Developer',
    category: 'Mid-size IT & engineering',
    hiringRoles: 'Full stack, SAP, cloud, testing, data/AI',
    careerPageUrl: 'https://hexaware.com/careers/',
    ctcEntry: '4 - 6 LPA',
    ctcExperienced: '7 - 16 LPA',
    salaryMin: 400000, salaryMax: 600000,
    location: 'Chennai / Multiple',
    skills: ['Full Stack', 'SAP', 'Cloud', 'Testing', 'Data Engineering', 'AI'],
    comments: 'Large Chennai presence.',
    minExp: 0, maxExp: 4,
  },
  {
    companyName: 'Coforge',
    jobTitle: 'Java/.NET Developer (BFSI)',
    category: 'Mid-size IT & engineering',
    hiringRoles: 'Java/.NET, data, cloud, QA',
    careerPageUrl: 'https://www.coforge.com/careers',
    ctcEntry: '4 - 6.5 LPA',
    ctcExperienced: '8 - 18 LPA',
    salaryMin: 400000, salaryMax: 650000,
    location: 'Multiple',
    skills: ['Java', '.NET', 'Data Engineering', 'Cloud', 'QA'],
    comments: 'Growing in BFSI, travel, insurance.',
    minExp: 0, maxExp: 4,
  },
  {
    companyName: 'Zensar',
    jobTitle: 'Full Stack / Cloud / Testing Engineer',
    category: 'Mid-size IT & engineering',
    hiringRoles: 'Full stack, cloud, data, testing',
    careerPageUrl: 'https://www.zensar.com/careers',
    ctcEntry: '3.5 - 6 LPA',
    ctcExperienced: '6 - 14 LPA',
    salaryMin: 350000, salaryMax: 600000,
    location: 'Pune / Bangalore',
    skills: ['Full Stack', 'Cloud', 'Data Engineering', 'Testing'],
    comments: 'Mostly Pune/Bangalore.',
    minExp: 0, maxExp: 3,
  },
  {
    companyName: 'Birlasoft',
    jobTitle: 'SAP / Oracle / Cloud Engineer',
    category: 'Mid-size IT & engineering',
    hiringRoles: 'SAP, Oracle, cloud, data',
    careerPageUrl: 'https://www.birlasoft.com/careers',
    ctcEntry: '3.5 - 5.5 LPA',
    ctcExperienced: '6 - 14 LPA',
    salaryMin: 350000, salaryMax: 550000,
    location: 'Multiple',
    skills: ['SAP', 'Oracle', 'Cloud', 'Data Engineering'],
    comments: 'ERP-focused.',
    minExp: 0, maxExp: 4,
  },
  {
    companyName: 'Sonata Software',
    jobTitle: '.NET / Azure / Dynamics Developer',
    category: 'Mid-size IT & engineering',
    hiringRoles: 'Microsoft stack (.NET/Azure/Dynamics), data',
    careerPageUrl: 'https://www.sonata-software.com/careers',
    ctcEntry: '4 - 6 LPA',
    ctcExperienced: '7 - 16 LPA',
    salaryMin: 400000, salaryMax: 600000,
    location: 'Multiple',
    skills: ['.NET', 'Azure', 'Dynamics 365', 'Data Engineering', 'Microsoft Stack'],
    comments: 'Microsoft-partner heavy; good for .NET/Azure profiles.',
    minExp: 0, maxExp: 4,
  },
  {
    companyName: 'Cyient',
    jobTitle: 'Embedded / Software Engineer (Engineering R&D)',
    category: 'Mid-size IT & engineering',
    hiringRoles: 'Embedded, software, engineering services',
    careerPageUrl: 'https://www.cyient.com/careers',
    ctcEntry: '3.5 - 5.5 LPA',
    ctcExperienced: '6 - 14 LPA',
    salaryMin: 350000, salaryMax: 550000,
    location: 'Multiple',
    skills: ['Embedded', 'C', 'C++', 'Software Engineering', 'Engineering Services'],
    comments: 'Engineering R&D.',
    minExp: 0, maxExp: 3,
  },
  {
    companyName: 'L&T Technology Services',
    jobTitle: 'Software Engineer (C/C++/Linux/Embedded)',
    category: 'Mid-size IT & engineering',
    hiringRoles: 'Software Engineer (C/C++, Linux, embedded)',
    careerPageUrl: 'https://www.larsentoubro.com/corporate/careers/',
    ctcEntry: 'up to 10 LPA',
    ctcExperienced: '8 - 18 LPA',
    salaryMin: 600000, salaryMax: 1000000,
    location: 'Multiple',
    skills: ['C', 'C++', 'Linux', 'Embedded', 'Software Engineering'],
    comments: 'Off-campus drive for Software Engineer (0-2 yrs) closed Oct 14.',
    minExp: 0, maxExp: 2,
  },
  // ── Big 4 & consulting tech ──────────────────────────────────────────────────
  {
    companyName: 'Deloitte',
    jobTitle: 'Analyst - Tech Strategy & Transformation',
    category: 'Big 4 & consulting tech',
    hiringRoles: 'Analyst, tech strategy & transformation, cloud, cyber',
    careerPageUrl: 'https://www.deloitte.com/in/en/careers.html',
    ctcEntry: '7 - 12 LPA',
    ctcExperienced: '12 - 25 LPA',
    salaryMin: 700000, salaryMax: 1200000,
    location: 'Bangalore / Hyderabad',
    skills: ['Cloud', 'Cybersecurity', 'Consulting', 'Tech Strategy', 'Transformation'],
    comments: 'Several Bangalore/Hyderabad analyst roles listed.',
    minExp: 0, maxExp: 3,
  },
  {
    companyName: 'KPMG',
    jobTitle: 'Tech Consulting / Cyber / Data & AI',
    category: 'Big 4 & consulting tech',
    hiringRoles: 'Tech consulting, cyber, data/AI',
    careerPageUrl: 'https://kpmg.com/in/en/careers.html',
    ctcEntry: '6 - 10 LPA',
    ctcExperienced: '10 - 22 LPA',
    salaryMin: 600000, salaryMax: 1000000,
    location: 'Multiple',
    skills: ['Consulting', 'Cybersecurity', 'Data Engineering', 'AI'],
    comments: 'Hires year-round.',
    minExp: 0, maxExp: 4,
  },
  {
    companyName: 'EY GDS',
    jobTitle: 'Tech Consulting / Cybersecurity / Data Engineer',
    category: 'Big 4 & consulting tech',
    hiringRoles: 'Tech consulting, cybersecurity, data',
    careerPageUrl: 'https://www.ey.com/en_in/careers',
    ctcEntry: '5 - 9 LPA',
    ctcExperienced: '9 - 20 LPA',
    salaryMin: 500000, salaryMax: 900000,
    location: 'Multiple',
    skills: ['Consulting', 'Cybersecurity', 'Data Engineering'],
    comments: 'Off-campus drives listed.',
    minExp: 0, maxExp: 3,
  },
  {
    companyName: 'PwC Acceleration Centers',
    jobTitle: 'Tech Consulting / Cloud / Cyber',
    category: 'Big 4 & consulting tech',
    hiringRoles: 'Tech consulting, cyber, cloud',
    careerPageUrl: 'https://www.pwc.in/careers.html',
    ctcEntry: '6 - 10 LPA',
    ctcExperienced: '10 - 22 LPA',
    salaryMin: 600000, salaryMax: 1000000,
    location: 'Bangalore / Kolkata / Mumbai',
    skills: ['Consulting', 'Cybersecurity', 'Cloud', 'Tech Strategy'],
    comments: 'Bangalore/Kolkata/Mumbai hubs.',
    minExp: 0, maxExp: 3,
  },
  // ── Product & big tech ───────────────────────────────────────────────────────
  {
    companyName: 'Microsoft India',
    jobTitle: 'Software Engineer (Azure / AI / Cloud)',
    category: 'Product & big tech',
    hiringRoles: 'SWE, cloud/Azure, AI, support engineering',
    careerPageUrl: 'https://careers.microsoft.com/',
    ctcEntry: '20 - 30 LPA',
    ctcExperienced: '30 - 65 LPA',
    salaryMin: 2000000, salaryMax: 3000000,
    location: 'Hyderabad / Bangalore',
    skills: ['Azure', 'AI', 'Cloud', 'C#', 'Python', 'Java', 'TypeScript'],
    comments: 'Hyderabad and Bangalore. Competitive.',
    minExp: 0, maxExp: 5,
  },
  {
    companyName: 'Amazon India',
    jobTitle: 'SDE I/II / Data Engineer / ML Engineer',
    category: 'Product & big tech',
    hiringRoles: 'SDE I/II, data engineer, cloud support, ML',
    careerPageUrl: 'https://www.amazon.jobs/',
    ctcEntry: '18 - 28 LPA',
    ctcExperienced: '35 - 70 LPA',
    salaryMin: 1800000, salaryMax: 2800000,
    location: 'Chennai / Bangalore / Hyderabad',
    skills: ['Java', 'Python', 'AWS', 'Data Engineering', 'Machine Learning', 'Distributed Systems'],
    comments: 'Chennai, Bangalore, Hyderabad.',
    minExp: 0, maxExp: 5,
  },
  {
    companyName: 'Google India',
    jobTitle: 'Software Engineer (SWE / Cloud / SRE)',
    category: 'Product & big tech',
    hiringRoles: 'SWE, cloud, SRE',
    careerPageUrl: 'https://www.google.com/about/careers/applications/',
    ctcEntry: '22 - 32 LPA',
    ctcExperienced: '40 - 80+ LPA',
    salaryMin: 2200000, salaryMax: 3200000,
    location: 'Bangalore / Hyderabad',
    skills: ['Python', 'Go', 'Java', 'C++', 'Cloud', 'SRE', 'Distributed Systems'],
    comments: 'Few India openings relative to demand.',
    minExp: 0, maxExp: 6,
  },
  {
    companyName: 'Oracle India',
    jobTitle: 'OCI / Java / Database / Cloud Engineer',
    category: 'Product & big tech',
    hiringRoles: 'OCI, Java, database, cloud engineers',
    careerPageUrl: 'https://careers.oracle.com/',
    ctcEntry: '12 - 20 LPA',
    ctcExperienced: '25 - 45 LPA',
    salaryMin: 1200000, salaryMax: 2000000,
    location: 'Bangalore / Hyderabad / Chennai',
    skills: ['Java', 'Oracle DB', 'OCI', 'Cloud', 'SQL', 'Python'],
    comments: 'Bangalore, Hyderabad, Chennai.',
    minExp: 0, maxExp: 5,
  },
  {
    companyName: 'Salesforce India',
    jobTitle: 'Software Engineer / Salesforce Developer (AI)',
    category: 'Product & big tech',
    hiringRoles: 'SWE, Salesforce dev, AI',
    careerPageUrl: 'https://careers.salesforce.com/',
    ctcEntry: '15 - 25 LPA',
    ctcExperienced: '30 - 50 LPA',
    salaryMin: 1500000, salaryMax: 2500000,
    location: 'Hyderabad / Bangalore',
    skills: ['Salesforce', 'Apex', 'JavaScript', 'AI', 'Python', 'Java'],
    comments: 'Hyderabad and Bangalore.',
    minExp: 0, maxExp: 5,
  },
  {
    companyName: 'Cisco India',
    jobTitle: 'Software Engineer (Networking / Cloud)',
    category: 'Product & big tech',
    hiringRoles: 'Software Engineer, networking, cloud',
    careerPageUrl: 'https://jobs.cisco.com/',
    ctcEntry: '14 - 22 LPA',
    ctcExperienced: '28 - 45 LPA',
    salaryMin: 1400000, salaryMax: 2200000,
    location: 'Bangalore',
    skills: ['Networking', 'Cloud', 'Python', 'C', 'C++', 'Go'],
    comments: 'Bangalore software engineer drive listed.',
    minExp: 0, maxExp: 5,
  },
  {
    companyName: 'Visa India',
    jobTitle: 'Software Engineer / Data Engineer',
    category: 'Product & big tech',
    hiringRoles: 'Software Engineer, data',
    careerPageUrl: 'https://corporate.visa.com/en/jobs',
    ctcEntry: '14 - 22 LPA',
    ctcExperienced: '28 - 45 LPA',
    salaryMin: 1400000, salaryMax: 2200000,
    location: 'Bangalore',
    skills: ['Java', 'Python', 'Data Engineering', 'SQL', 'Distributed Systems'],
    comments: 'Bangalore. Software Engineer role listed.',
    minExp: 0, maxExp: 5,
  },
  {
    companyName: 'Walmart Global Tech India',
    jobTitle: 'Software Engineer II (Platform / Data)',
    category: 'Product & big tech',
    hiringRoles: 'Software Engineer II, data, platform',
    careerPageUrl: 'https://careers.walmart.com/',
    ctcEntry: '20 - 35 LPA',
    ctcExperienced: '35 - 65 LPA',
    salaryMin: 2000000, salaryMax: 3500000,
    location: 'Chennai / Bangalore',
    skills: ['Java', 'Scala', 'Python', 'Big Data', 'Kafka', 'Cloud', 'Kubernetes'],
    comments: 'SE II role in Chennai & Bangalore listed (older page, verify).',
    minExp: 1, maxExp: 5,
  },
  {
    companyName: 'Zoho',
    jobTitle: 'Developer / Member of Technical Staff (AI/ML)',
    category: 'Product & big tech',
    hiringRoles: 'Developers, MTS, support engineers, AI/ML',
    careerPageUrl: 'https://www.zoho.com/careers/',
    ctcEntry: '4 - 12 LPA',
    ctcExperienced: '15 - 25 LPA',
    salaryMin: 400000, salaryMax: 1200000,
    location: 'Chennai',
    skills: ['Java', 'Python', 'AI', 'ML', 'Full Stack', 'Product Engineering'],
    comments: 'Chennai HQ. Strong local product-engineering culture.',
    minExp: 0, maxExp: 4,
  },
  {
    companyName: 'Freshworks',
    jobTitle: 'SDE / SRE / Data & AI Engineer',
    category: 'Product & big tech',
    hiringRoles: 'SDE, SRE, data, AI',
    careerPageUrl: 'https://www.freshworks.com/company/careers/',
    ctcEntry: '10 - 18 LPA',
    ctcExperienced: '22 - 40 LPA',
    salaryMin: 1000000, salaryMax: 1800000,
    location: 'Chennai',
    skills: ['Ruby', 'Go', 'React', 'Python', 'SRE', 'Data Engineering', 'AI'],
    comments: 'Chennai HQ.',
    minExp: 0, maxExp: 5,
  },
  {
    companyName: 'Chargebee',
    jobTitle: 'Full Stack / Backend / SRE Engineer',
    category: 'Product & big tech',
    hiringRoles: 'Full stack, backend, SRE',
    careerPageUrl: 'https://www.chargebee.com/company/careers/',
    ctcEntry: '10 - 16 LPA',
    ctcExperienced: '20 - 35 LPA',
    salaryMin: 1000000, salaryMax: 1600000,
    location: 'Chennai',
    skills: ['Full Stack', 'Backend', 'SRE', 'Ruby', 'Node.js', 'React', 'AWS'],
    comments: 'Chennai-based SaaS.',
    minExp: 0, maxExp: 4,
  },
  {
    companyName: 'KLA',
    jobTitle: 'Software / Embedded Engineer (Fresher Program)',
    category: 'Product & big tech',
    hiringRoles: 'Software, embedded, fresher program',
    careerPageUrl: 'https://www.kla.com/careers',
    ctcEntry: '8 - 14 LPA',
    ctcExperienced: '18 - 35 LPA',
    salaryMin: 800000, salaryMax: 1400000,
    location: 'Chennai',
    skills: ['Software Engineering', 'Embedded', 'C', 'C++', 'Python'],
    comments: 'Chennai fresher role (2024-2026 batches) listed.',
    minExp: 0, maxExp: 2,
  },
  // ── GCC (Chennai-focused) ────────────────────────────────────────────────────
  {
    companyName: 'Starbucks GCC Chennai',
    jobTitle: 'Tech / Engineering / Data / Cloud Engineer',
    category: 'GCC (Chennai-focused)',
    hiringRoles: 'Tech roles: engineering, data, cloud',
    careerPageUrl: 'https://www.starbucks.com/careers',
    ctcEntry: '10 - 18 LPA (typical GCC band)',
    ctcExperienced: '20 - 40 LPA',
    salaryMin: 1000000, salaryMax: 1800000,
    location: 'Chennai',
    skills: ['Engineering', 'Data Engineering', 'Cloud', 'Python', 'AWS'],
    comments: 'Planned Chennai GCC, ~800 tech jobs. Early stage; postings may be limited now.',
    minExp: 0, maxExp: 6,
  },
  {
    companyName: 'Walgreens GCC Chennai',
    jobTitle: 'Tech & Digital Engineering Roles',
    category: 'GCC (Chennai-focused)',
    hiringRoles: 'Tech and digital roles',
    careerPageUrl: 'https://jobs.walgreens.com/',
    ctcEntry: '10 - 18 LPA (typical GCC band)',
    ctcExperienced: '20 - 40 LPA',
    salaryMin: 1000000, salaryMax: 1800000,
    location: 'Chennai',
    skills: ['Software Engineering', 'Digital', 'Cloud', 'Data Engineering'],
    comments: 'Announced just before Starbucks. Watch for postings in coming months.',
    minExp: 0, maxExp: 6,
  },
  {
    companyName: 'Chubb',
    jobTitle: 'Insurance Platform & Digital Engineering',
    category: 'GCC (Chennai-focused)',
    hiringRoles: 'Insurance platform & digital engineering',
    careerPageUrl: 'https://careers.chubb.com/',
    ctcEntry: '8 - 14 LPA',
    ctcExperienced: '16 - 30 LPA',
    salaryMin: 800000, salaryMax: 1400000,
    location: 'Chennai',
    skills: ['Insurance Tech', 'Digital Engineering', 'Java', 'Cloud', 'API'],
    comments: 'First Chennai GCC announced July 2026, 220 jobs.',
    minExp: 0, maxExp: 6,
  },
  {
    companyName: 'UPS',
    jobTitle: 'Logistics Tech / Data / Engineering',
    category: 'GCC (Chennai-focused)',
    hiringRoles: 'Logistics tech, data, engineering',
    careerPageUrl: 'https://www.jobs-ups.com/',
    ctcEntry: '8 - 14 LPA',
    ctcExperienced: '16 - 30 LPA',
    salaryMin: 800000, salaryMax: 1400000,
    location: 'Chennai',
    skills: ['Logistics Tech', 'Data Engineering', 'Python', 'Java', 'Cloud'],
    comments: 'Phase 3 facility at Chennai GCC (May 2026).',
    minExp: 0, maxExp: 6,
  },
  {
    companyName: 'FIS',
    jobTitle: 'Fintech Engineering / AI Engineer',
    category: 'GCC (Chennai-focused)',
    hiringRoles: 'Fintech engineering, AI',
    careerPageUrl: 'https://jobs.fisglobal.com/',
    ctcEntry: '8 - 14 LPA',
    ctcExperienced: '16 - 32 LPA',
    salaryMin: 800000, salaryMax: 1400000,
    location: 'Bengaluru / Chennai',
    skills: ['Fintech', 'AI', 'Java', 'Python', 'Cloud', 'Security'],
    comments: 'Expanding GCC for secure AI solutions (Bengaluru & Chennai).',
    minExp: 0, maxExp: 6,
  },
  {
    companyName: 'Workday',
    jobTitle: 'AI & Cloud Engineer (Chennai GCC)',
    category: 'GCC (Chennai-focused)',
    hiringRoles: 'AI and cloud engineers',
    careerPageUrl: 'https://www.workday.com/en-us/company/careers.html',
    ctcEntry: '18 - 28 LPA',
    ctcExperienced: '35 - 60 LPA',
    salaryMin: 1800000, salaryMax: 2800000,
    location: 'Chennai',
    skills: ['AI', 'Cloud', 'Java', 'Python', 'Machine Learning', 'Workday Platform'],
    comments: '~Rs 220 crore Chennai GCC for next-gen AI.',
    minExp: 0, maxExp: 6,
  },
  {
    companyName: 'AstraZeneca',
    jobTitle: 'Data / Cloud / Clinical-Data Technology',
    category: 'GCC (Chennai-focused)',
    hiringRoles: 'Data, cloud, clinical-data tech',
    careerPageUrl: 'https://careers.astrazeneca.com/',
    ctcEntry: '8 - 14 LPA',
    ctcExperienced: '16 - 30 LPA',
    salaryMin: 800000, salaryMax: 1400000,
    location: 'Chennai',
    skills: ['Data Engineering', 'Cloud', 'Clinical Data', 'Python', 'AWS', 'Bioinformatics'],
    comments: 'Chennai GCC is now its largest worldwide.',
    minExp: 0, maxExp: 6,
  },
  {
    companyName: 'Standard Chartered',
    jobTitle: 'Full Stack / Cloud / Data / Cyber Engineer',
    category: 'GCC (Chennai-focused)',
    hiringRoles: 'Full stack, cloud, data, cyber',
    careerPageUrl: 'https://www.sc.com/en/careers/',
    ctcEntry: '8 - 14 LPA',
    ctcExperienced: '18 - 35 LPA',
    salaryMin: 800000, salaryMax: 1400000,
    location: 'Chennai',
    skills: ['Full Stack', 'Cloud', 'Data Engineering', 'Cybersecurity', 'Java', 'Python'],
    comments: 'Large Chennai GBS.',
    minExp: 0, maxExp: 6,
  },
  {
    companyName: 'Barclays',
    jobTitle: 'Technology & Operations Engineer',
    category: 'GCC (Chennai-focused)',
    hiringRoles: 'Technology and operations',
    careerPageUrl: 'https://search.jobs.barclays/',
    ctcEntry: '8 - 14 LPA',
    ctcExperienced: '18 - 35 LPA',
    salaryMin: 800000, salaryMax: 1400000,
    location: 'Chennai',
    skills: ['Java', 'Python', 'Cloud', 'Data Engineering', 'Banking Tech'],
    comments: 'Listed as expanding in 2026; Global Service Centre sites include Chennai.',
    minExp: 0, maxExp: 6,
  },
  {
    companyName: 'Citi',
    jobTitle: 'Java/.NET Full Stack / Data / Cloud Engineer',
    category: 'GCC (Chennai-focused)',
    hiringRoles: 'Java/.NET full stack, data, cloud',
    careerPageUrl: 'https://jobs.citi.com/',
    ctcEntry: '8 - 14 LPA',
    ctcExperienced: '18 - 35 LPA',
    salaryMin: 800000, salaryMax: 1400000,
    location: 'Chennai',
    skills: ['Java', '.NET', 'Full Stack', 'Data Engineering', 'Cloud'],
    comments: 'Big Chennai tech hub.',
    minExp: 0, maxExp: 6,
  },
  {
    companyName: 'American Express',
    jobTitle: 'Engineering / Data & ML Engineer',
    category: 'GCC (Chennai-focused)',
    hiringRoles: 'Engineering, data/ML',
    careerPageUrl: 'https://www.americanexpress.com/en-in/careers/',
    ctcEntry: '10 - 16 LPA',
    ctcExperienced: '20 - 38 LPA',
    salaryMin: 1000000, salaryMax: 1600000,
    location: 'Chennai',
    skills: ['Java', 'Python', 'Machine Learning', 'Data Engineering', 'Cloud'],
    comments: 'Chennai tech centre.',
    minExp: 0, maxExp: 5,
  },
  {
    companyName: 'PayPal',
    jobTitle: 'Full Stack / Backend / Data / SRE Engineer',
    category: 'GCC (Chennai-focused)',
    hiringRoles: 'Full stack, backend, data, SRE',
    careerPageUrl: 'https://paypal.eightfold.ai/',
    ctcEntry: '16 - 24 LPA',
    ctcExperienced: '30 - 45 LPA',
    salaryMin: 1600000, salaryMax: 2400000,
    location: 'Chennai',
    skills: ['Full Stack', 'Backend', 'Data Engineering', 'SRE', 'Java', 'Python', 'Node.js'],
    comments: 'Chennai tech centre.',
    minExp: 0, maxExp: 5,
  },
  {
    companyName: 'Ford Global Tech Centre',
    jobTitle: 'Software / Data / Cloud / Automotive Tech',
    category: 'GCC (Chennai-focused)',
    hiringRoles: 'Software, data, cloud, automotive tech',
    careerPageUrl: 'https://corporate.ford.com/careers',
    ctcEntry: '7 - 12 LPA',
    ctcExperienced: '15 - 28 LPA',
    salaryMin: 700000, salaryMax: 1200000,
    location: 'Chennai',
    skills: ['Software Engineering', 'Data Engineering', 'Cloud', 'Automotive Tech', 'Python', 'C++'],
    comments: 'Large Chennai operation.',
    minExp: 0, maxExp: 6,
  },
];

const seed = async () => {
  const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/job_dashboard';
  await mongoose.connect(uri);
  console.log(`[SeedIndiaJobs] Connected to ${uri}`);

  let inserted = 0;
  let skipped = 0;

  for (const j of INDIA_JOBS) {
    const jobUrl = j.careerPageUrl;
    const uniqueHash = generateJobHash(j.companyName, j.jobTitle, jobUrl);

    const exists = await Job.findOne({ uniqueHash });
    if (exists) {
      console.log(`[SeedIndiaJobs] SKIP (exists): ${j.companyName} - ${j.jobTitle}`);
      skipped++;
      continue;
    }

    const description =
      `[${j.category}] ${j.hiringRoles}. ` +
      `Entry-level CTC: ${j.ctcEntry}. ` +
      `Experienced CTC (3-6 yrs): ${j.ctcExperienced}. ` +
      `Location: ${j.location}. ` +
      `Skills: ${j.skills.join(', ')}. ` +
      `Notes: ${j.comments}`;

    await Job.create({
      companyName: j.companyName,
      companyWebsite: j.careerPageUrl,
      careerPageUrl: j.careerPageUrl,
      jobTitle: j.jobTitle,
      jobDescription: description,
      jobUrl,
      location: j.location,
      remote: j.location.toLowerCase().includes('remote'),
      employmentType: 'Full-time',
      experienceRequired: `${j.minExp}-${j.maxExp} years`,
      minExperienceYears: j.minExp,
      maxExperienceYears: j.maxExp,
      salary: {
        min: j.salaryMin,
        max: j.salaryMax,
        currency: 'INR',
        period: 'yearly',
      },
      skills: j.skills,
      requiredSkills: j.skills,
      source: 'Company Career Page',
      postedDate: new Date('2026-10-01'),
      uniqueHash,
      status: 'new',
      matchScore: 0,
    });

    console.log(`[SeedIndiaJobs] Inserted: ${j.companyName} - ${j.jobTitle}`);
    inserted++;
  }

  console.log(`\n[SeedIndiaJobs] Done! Inserted: ${inserted}, Skipped: ${skipped}`);
  process.exit(0);
};

seed().catch((err) => {
  console.error('[SeedIndiaJobs] Failed:', err);
  process.exit(1);
});
