import express from 'express';
import { getCompanies, createCompany, updateCompany, deleteCompany, scanCompanyJobs, getCompanyJobs } from '../controllers/companyController.js';
import { protect } from '../middleware/auth.js';
const router = express.Router();
router.use(protect);
router.get('/', getCompanies);
router.post('/', createCompany);
router.put('/:id', updateCompany);
router.delete('/:id', deleteCompany);
router.post('/:id/scan', scanCompanyJobs);
router.get('/:id/jobs', getCompanyJobs);
export default router;
