import express from 'express';
import { uploadResume, getResumes, getResume, updateResumeProfile, deleteResume, analyzeResume, customizeResumeForJob, downloadResumePdf } from '../controllers/resumeController.js';
import { getVersions, getVersion, deleteVersion, downloadVersionPdf, setPrimary } from '../controllers/resumeVersionController.js';
import { protect } from '../middleware/auth.js';
import { uploadResume as upload } from '../middleware/upload.js';
const router = express.Router();
router.use(protect);
router.post('/', upload.single('resume'), uploadResume);
router.get('/', getResumes);
router.post('/:id/analyze', analyzeResume);
router.post('/:id/customize', customizeResumeForJob);
router.get('/:id/versions', getVersions);
router.get('/:id/download.pdf', downloadResumePdf);
router.get('/:id', getResume);
router.put('/:id', updateResumeProfile);
router.delete('/:id', deleteResume);
router.get('/versions/:versionId', getVersion);
router.put('/versions/:versionId/primary', setPrimary);
router.delete('/versions/:versionId', deleteVersion);
router.get('/versions/:versionId/download.pdf', downloadVersionPdf);
export default router;
